before:
  hooks:
    - go mod tidy

builds:
  - goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X {{.ModulePath}}/meta.Version={{.Version}} -X {{.ModulePath}}/meta.Commit={{.Commit}} -X {{.ModulePath}}/meta.BuildDate={{.Date}}

dockers:
    - goos: linux
      goarch: amd64
      image_templates:
      - ghcr.io/einfach-gaming/egmrp-daemon:latest-amd64
      - ghcr.io/einfach-gaming/egmrp-daemon:{{ .Tag }}-amd64
    - goos: linux
      goarch: arm64
      image_templates:
      - ghcr.io/einfach-gaming/egmrp-daemon:latest-arm64
      - ghcr.io/einfach-gaming/egmrp-daemon:{{ .Tag }}-arm64

docker_manifests:
  - name_template: ghcr.io/einfach-gaming/egmrp-daemon:{{ .Tag }}
    image_templates:
      - ghcr.io/einfach-gaming/egmrp-daemon:{{ .Tag }}-amd64
      - ghcr.io/einfach-gaming/egmrp-daemon:{{ .Tag }}-arm64
  - name_template: ghcr.io/einfach-gaming/egmrp-daemon:latest
    image_templates:
      - ghcr.io/einfach-gaming/egmrp-daemon:latest-amd64
      - ghcr.io/einfach-gaming/egmrp-daemon:latest-arm64
